- spec/loophp/collection/CollectionSpec.php
- src/Operation/Group.php
> Update Group operation. (Fix #19)

- docs/pages/usage.rst
This PR
Updates the documentation.
Fixes #22 .
> Updated append method documentation.

- spec/loophp/collection/CollectionSpec.php
- src/Operation/Has.php
> Fix Has operation.

- docs/pages/usage.rst
> Fix simple code examples path

- composer.json
- docs/pages/api.rst
- spec/loophp/collection/CollectionSpec.php
- src/Collection.php
- src/Contract/Collection.php
- src/Contract/Operation/AsyncMapable.php
- src/Operation/AsyncMap.php
- src/Operation/Map.php
This PR
Related to https://github.com/amphp/parallel-functions/issues/25
> New asyncMap() operation (featuring amphp!)

- .github/workflows/code-style.yml
- .github/workflows/mutation-tests.yml
- .github/workflows/release.yaml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
- composer.json
- infection.json
> ci: Split CI files

- spec/loophp/collection/CollectionSpec.php
- spec/loophp/collection/Iterator/RandomIteratorSpec.php
- src/Collection.php
- src/Iterator/RandomIterator.php
- src/Operation/Distinct.php
- src/Operation/Random.php
- src/Operation/Shuffle.php
> Add $seed parameter to RandomIterator

- spec/loophp/collection/CollectionSpec.php
- spec/loophp/collection/Iterator/ArrayCacheIteratorSpec.php
- spec/loophp/collection/Iterator/PsrCacheIteratorSpec.php
- spec/loophp/collection/Iterator/RandomIteratorSpec.php
- src/Collection.php
- src/Iterator/ArrayCacheIterator.php
- src/Iterator/ClosureIterator.php
- src/Iterator/IterableIterator.php
- src/Iterator/ProxyIterator.php
- src/Iterator/PsrCacheIterator.php
- src/Iterator/RandomIterator.php
- src/Iterator/ResourceIterator.php
- src/Iterator/StringIterator.php
- src/Operation/Cache.php
> Iterators refactoring

- docs/pages/api.rst
- spec/loophp/collection/CollectionSpec.php
- src/Operation/Apply.php
> fix: Update behavior of Apply operation.

- docs/pages/api.rst
- spec/loophp/collection/CollectionSpec.php
- src/Collection.php
- src/Contract/Collection.php
- src/Contract/Operation/Dumpable.php
- src/Operation/Dump.php
> feat: Add Dump operation.

- .github/settings.yml
- .github/workflows/code-style.yml
- .github/workflows/mutation-tests.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
> Fix CI configuration.

- composer.json
- spec/loophp/collection/CollectionSpec.php
> Bump minimum version of phpspec to ^7.1.

- .github/workflows/tests.yml
- grumphp.yml
- spec/loophp/collection/CollectionSpec.php
- spec/loophp/collection/Iterator/MultipleIterableIteratorSpec.php
- spec/loophp/collection/Iterator/StringIteratorSpec.php
- src/Iterator/MultipleIterableIterator.php
> Add coverage check

- src/Operation/Reject.php
> refactor: Update `Reject` operation - add missing type hints.

- src/Operation/Pipe.php
Explanations: https://www.freecodecamp.org/news/how-point-free-composition-will-make-you-a-better-functional-programmer-33dcb910303a/
> refactor: Use point free for the `Pipe` operation (ETA reduction)

- src/Operation/Unpack.php
> refactor: Update `Unpack` operation - do not use `MapN`.

- src/Operation/Collapse.php
> refactor: Update `Collapse` operation in point free style.

- src/Operation/Associate.php
- src/Operation/DropWhile.php
- src/Operation/Filter.php
- src/Operation/Since.php
- src/Operation/TakeWhile.php
- src/Operation/Until.php
- src/Operation/When.php
> refactor: Minor optimizations in various operations.

- docs/pages/api.rst
- docs/pages/code/operations/combine.php
- spec/loophp/collection/CollectionSpec.php
- src/Contract/Operation/Combineable.php
- src/Operation/Combine.php
- src/Operation/Reverse.php
> refactor: Update `combine` operation in point free style.

- phpstan-baseline.neon
- src/Operation/Unwindow.php
- tests/static-analysis/all.php
- tests/static-analysis/flip.php
- tests/static-analysis/random.php
- tests/static-analysis/shuffle.php
- tests/static-analysis/unpack.php
- tests/static-analysis/wrap.php
> [PHPStan Baseline] A few small fixes

- composer.json
- docs/pages/tests.rst
- tests/unit/Iterator/PsrCacheIteratorTest.php
> Get rid of `phpspec/prophecy-phpunit`.

- .scrutinizer.yml
- src/Operation/Combine.php
This PR:
Follows #.
Related to #.
Fixes #.
> Update Scrutinizer configuration.

- .github/workflows/mutation-tests.yml
- .github/workflows/tests.yml
- infection.json
- phpunit.xml
This PR:
Follows #.
Related to #.
Fixes #.
> ci: Use `pcov` for coverage.

- .editorconfig
- .github/workflows/code-style.yml
- .github/workflows/mutation-tests.yml
- .github/workflows/readme.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
- .prettierrc
- README.md
This PR:
Follows #.
Related to #.
Fixes #.
> Add action on README file.

- .editorconfig
- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .prettierignore
- README.md
- docs/index.rst
- docs/pages/api.rst
- docs/pages/code/operations/background.php
- docs/pages/code/operations/contains.php
- docs/pages/code/operations/filter.php
- docs/pages/code/operations/reject.php
- docs/pages/code/serialization.php
- docs/pages/code/simple.php
- docs/pages/code/string.php
- docs/pages/contributing.rst
- docs/pages/principles.rst
- docs/pages/requirements.rst
- docs/pages/tests.rst
- docs/pages/usage.rst
- src/Contract/Operation/Sortable.php
> Documentation: refactoring

- src/Collection.php
- src/Operation/Combinate.php
- src/Operation/Permutate.php
- src/Operation/Tails.php
- tests/static-analysis/all.php
- tests/static-analysis/append.php
- tests/static-analysis/asyncMap.php
- tests/static-analysis/distinct.php
- tests/static-analysis/drop.php
- tests/static-analysis/flatMap.php
- tests/static-analysis/flip.php
- tests/static-analysis/keys.php
- tests/static-analysis/lines.php
- tests/static-analysis/normalize.php
- tests/static-analysis/pair.php
- tests/static-analysis/random.php
- tests/static-analysis/shuffle.php
- tests/static-analysis/squash.php
- tests/static-analysis/unfold.php
- tests/static-analysis/wrap.php
> Psalm 5 upgrade

- .github/workflows/static-analysis.yml
- tests/unit/CustomCollectionConstructorsTest.php
> tests: Update to PHPUnit 10
